Fix/cmr 6856 catalog child links
nasa/cmr-stac pull request #100
Opened 2020-11-09 15:33 UTC by matthewhanson

2020-11-09 16:38 UTC, jaybarra commented on search/lib/api/provider.js
>      response.status(200).json(provider);
`.status(200)` is redundant when using `.json` unless you need to set a different one

2020-11-09 16:43 UTC, daniel-zamora approved these changes

2020-11-09 16:44 UTC, jaybarra requested changes
I don't see the new test in the build results. If there are tests are deeper levels they might be be being executed.

2020-11-09 16:44 UTC, jaybarra commented on search/tests/api/provider.spec.js
> +    dat.json.links = dat.json.links.slice(0, 4);
Is a test being done with this?

2020-11-09 16:58 UTC, jaybarra approved these changes
Ignore the comment about the tests. Just remove the unused dat slice unless there is something testing it.

2020-11-10 06:18 UTC, matthewhanson commented
> Ignore the comment about the tests. Just remove the unused dat slice unless there is something testing it.

@jaybarra This PR adds a bunch of 'child' links to every root provider catalog. Before, the provider catalog only contained a handful of deterministic links (self, root, parent, collections, search). But now there are links for all the collections in a provider.

I recognize that this makes it not a test for the child links, but I don't want to have a fixture of all the collections in a test provider because this could easily change. Maybe a test to check that there is some minimum # of child links would be sufficient.

2020-11-10 18:33 UTC, merged