[CMR-6779] return empty facets if no granules
nasa/cmr-stac pull request #127
Opened 2021-02-02 06:20 UTC by matthewhanson

Fixes problem in previous PR that updated to use new collection IDs, where an error was thrown if the collection had no granules

2021-02-02 14:02 UTC, ygliuvt commented
looks like there are test failures.

2021-02-02 14:10 UTC, mschmele reviewed
I'm not a fan of nested `if` statements, but I don't think there's another sane way to do this - I'll approve once the tests pass

2021-02-02 14:15 UTC, jaybarra commented
Would recommend pulling out the first `if` block into a separate function

2021-02-02 14:41 UTC, jaybarra requested changes
Would recommend pulling out the first if content block into a separate function

2021-02-04 15:38 UTC, jaybarra approved these changes

2021-02-08 02:13 UTC, merged