CMR-7167: Removed the hardcoded pageSize in getProvider and getCollections
nasa/cmr-stac pull request #139
Opened 2021-02-25 21:12 UTC by sxu123

This is to fix the pagination next link.

2021-02-25 22:38 UTC, matthewhanson approved these changes

2021-02-25 22:47 UTC, matthewhanson approved these changes

2021-02-26 13:29 UTC, jaybarra requested changes

2021-02-26 13:29 UTC, jaybarra commented on search/lib/api/provider.js
> +    const pageSize = request.query.limit || 10;
Should move the `Number` conversion here so the `const pageSize` is always a number type

2021-03-01 14:24 UTC, jaybarra approved these changes

2021-03-01 15:48 UTC, merged